### ISSUE TITLE
Migrate to C++20?

### ISSUE THREAD

**Issue by fengwang** [lidotcircle/curly#1]
The widely employed SFINAE idioms are quite tricky to read, maybe concept is a good replacement?

For example,

https://github.com/lidotcircle/curly/blob/6d6c727726be0ee85501e424802c5dacf4248de8/include/rbtree.hpp#L115

can be rewriten to

```cpp
template<RBTreeValueKV T, Compare C >
```

**Comment by lidotcircle** [comment]
I will do that, but I need sometime to grasp c++20 concept

**Comment by lidotcircle** [comment]
SFINAE has been replaced with concepts for c++20 in [v1.0](https://github.com/lidotcircle/curly/releases/tag/v1.0). 
[rbtree_20.hpp](https://github.com/lidotcircle/curly/releases/download/v1.0/rbtree_20.hpp) is more concise version which  removes preprocessor conditional directives those contain __cplusplus by unifdef.
